ALTER TABLE IF EXISTS users ALTER COLUMN role VARCHAR(20);
UPDATE users SET role = 'USER' WHERE role = 'PARENT';
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS blocked BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE IF EXISTS programs ADD COLUMN IF NOT EXISTS image_path VARCHAR(255);
